name: Next.js CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.repository == 'PhantomOfLINUX/POL_Front'
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/pol-front:latest
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/pol-front:cache
        cache-to: type=inline
        
  deploy:
      needs: build
      runs-on: ubuntu-20.04
      if: github.repository == 'PhantomOfLINUX/POL_Front'
      steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pol-front:latest
            docker stop pol-front || true
            docker rm pol-front || true
            docker run -d --name pol-front -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/pol-front:latest
